### ISSUE TITLE
ES6 modules

### ISSUE THREAD

**Issue by alippai** [asmcrypto/asmcrypto.js#119]
Should we change the build to ES2015 modules + rollup?

**Comment by alippai** [comment]
Also the wrapper to use ES6 classes

**Comment by vibornoff** [comment]
Does it compatible with old browsers: IE10, Safari 5.1?

**Comment by jdonaldson10** [comment]
@alippai I actually spent a couple of hours working on this yesterday and have it about 85% of the way there.

I've tried to do this with minimal disruption to the code. As such there isn't any es6 class syntax yet but that could be added if we want Also the current `*/exports.js` could probably be refactored away.

I've tended to towarda `default export` to keep the public api/namespaceing isolated within the `index.js`. Then if other want a custom build they can then easily `import` in the specific functions they need direct from source and let their project's module builder handle it all. Doing this probably solves #88 #102 and removes the need for the OpenPGP.js team's seperate fork as per #95 

More importantly it removes the need for the massive dependency list in the current `gruntfile.js` as every module describes it's own dependencies :ok_hand:

I can likely have something PR worthy by the weekend if that's acceptable?

## So far:
- [x] moved to rollup
- [x] babel transpilation
- [x] added a new `index.js` to the source that contains all the public exports to mimic the current build
- [x] have each js file describe their sepcific dependencies with es6 `import { ... }` to allow rollup to draw an accurate dependency tree
- [x] umd output
- [x] minification
- [x] sourcemaps
- [x] copyright info
- [x] added `build` & `watch` commands for a dev experience consitent with [rollup's recommendations](https://github.com/rollup/rollup-starter-project) 

## Bundle Size
- Initial indicators show comparable bundle size `~180KB`  😄
- Exporting a specific RSA encryption function was coming out `~30KB`

## TODO
- [ ] Validate all the tests are passing (currently 60% through this)
- [ ] Fixes require for the above
- [ ] Remove all remnants of `grunt`
- [ ] Output a separate `asmcrypto.min.js` file as part of the build? 
- [ ] Do we still want our tests running through phantom? Perhaps karma would be a better choice these days?



What do you think about adding some code coverage with `istanbul` and code quality stuff with `eslint`? Maybe best leaving those to separate issues as they could be quite time consuming to implement be quite impacting on the codebase.

**Comment by alippai** [comment]
The rollup can produce iife and amd/commonjs code. The classes are not
supported only after transpiling with Babel.

Both improvements help the developer experience and IDE support.

**Comment by alippai** [comment]
Awesome!

**Comment by jdonaldson10** [comment]
@vibornoff yes. By having having the bable transpile step the output is an ES5 compatiable UMD as per the current setup

**Comment by vibornoff** [comment]
- [x] rollup
- [x] babel
- [x] ~grunt~
- [ ] gulp in place of grunt?
- [ ] karma with saucelabs.com runner
- [ ] add nodejs runner for tests (some folks use asmCrypto inside nodejs)

BTW, why you guys don't use modern WebCrypto API?

**Comment by alippai** [comment]
I use it for streaming SHA, buggy Firefox crypto in FF45 (ESR) and pbkdf,
rsa pss (missing in IE11)

**Comment by jdonaldson10** [comment]
I'm not convinced we need any task runner really. Some simple npm scripts to orchestrate our module bundler/test runner should be enough and save an extra dependency
```js
// package.json
{
  /* ... */
  "scripts": {
    "prebuild": "eslint lib test",
    "build": "rollup -c",
    "watch": "rollup -c -w",
    "pretest": "npm run build",
    "test": "karma .....",
    "prepublish": "npm test"
  }
  /* ... */
}
```
As for webcrypto, yea I'm with you on that one. More of a side interest and some awkward corner cases.

**Comment by vibornoff** [comment]
Ok guys, I'd be glad to see your PRs! 👍

**Comment by alippai** [comment]
@jdonaldson10 can you push your changes so I can help with testing and further work?

**Comment by jdonaldson10** [comment]
Been a little swamped this past couple of weeks so haven't progressed as much as I'd hoped. In saying that I have the tests all passing locally.

Hopefully I can get sometime later today/tomorrow to bring it together

**Comment by alippai** [comment]
@jdonaldson10 I'd be happy if I could help your work in any way. Ping me, if you need help testing or in development.
